CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL UNIQUE,
    slug VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE game_tag_assignments (
    game_id VARCHAR(36) NOT NULL
        REFERENCES games(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL
        REFERENCES tags(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL
        REFERENCES app_user(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_game_tag_assignments
        PRIMARY KEY (game_id, tag_id, user_id)
);

CREATE INDEX idx_game_tag_assignments_tag_game
    ON game_tag_assignments(tag_id, game_id);

INSERT INTO tags (name, slug) VALUES
    ('Action', 'action'),
    ('Adventure', 'adventure'),
    ('Arcade', 'arcade'),
    ('Fighting', 'fighting'),
    ('Horror', 'horror'),
    ('Platformer', 'platformer'),
    ('Puzzle', 'puzzle'),
    ('Racing', 'racing'),
    ('RPG', 'rpg'),
    ('Roguelike', 'roguelike'),
    ('Shooter', 'shooter'),
    ('Simulation', 'simulation'),
    ('Sports', 'sports'),
    ('Strategy', 'strategy'),
    ('Casual', 'casual');